### PR TITLE
i added this (the KEYWORD) and it's actually goddamn useful

### PR DESCRIPTION
**Pull request by LordScarvius**
THIS

### CODE REVIEW

**Comment by LordScarvius** [comment]
accept this PR of mine

**Comment by LordScarvius** [comment]
don't you love this?

**Comment by LordScarvius** [comment]
this is amazing

**Comment by LordScarvius** [comment]
accept this

**Comment by DiMino-0** [comment]
this is super

**Comment by LordScarvius** [comment]
thanks for this

**Pull request merged**
